---
abstract: 'tiny object system with privacy settings for properties and methods, abstract classes and methods, exceptions'
author:
  - 'Georgy Bazhukov <georgy.bazhukov@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150001'
keywords:
  - Class
  - Object
  - Method
  - OOP
  - Private
  - Protected
  - Abstract
  - Interface
  - Exception
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pony-Object
provides:
  Pony::Object:
    file: lib/Pony/Object.pm
    version: '1.01'
  Pony::Object::Throwable:
    file: lib/Pony/Object/Throwable.pm
  Pony::Object::TieStatic:
    file: lib/Pony/Object.pm
requires:
  Carp: '0'
  Module::Load: '0'
  Scalar::Util: '0'
  Storable: '0'
  perl: '5.012'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/bugov/pony-object
version: '1.01'
