#!/usr/bin/env perl

use strict;
use warnings;
use feature ':5.10';

while ( <STDIN> )
{
    # Remove rubbish lines.
    s/^commit.*?\n//is;
    s/^Author.*?\n//is;
    s/^Date:\s*//is;
    
    print
}
